## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('csma-duplex', ['node'])
    obj.source = [
        'csma-duplex-net-device.cc',
        'csma-duplex-channel.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'csma-duplex'
    headers.source = [
        'csma-duplex-net-device.h',
        'csma-duplex-channel.h',
        ]
